name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test-vers:
    strategy:
      matrix:
        # The lowest supported version, as a sanity check, plus current releases
        # of Node.js: https://github.com/nodejs/release
        node: ['8', '16', '18', '20']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm test
